### ISSUE TITLE
set up google analytics on codeforvallejo.org

### ISSUE THREAD

**Issue by andrewschneider** [codeforamerica/Vallejo_waffle#55]

**Comment by nikzei** [comment]
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-61790206-1', 'auto');
  ga('send', 'pageview');

put a script in the beginning and a /script n the end
